# Generated by Django 5.0.2 on 2024-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.CharField(default='Agent', help_text='SNMP role: Manager / Agent', max_length=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=False, help_text='Device status: Active / Inactive'),
        ),
    ]
