# Generated by Django 5.0.2 on 2024-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_panel', '0002_host_role_alter_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hdd_total',
            field=models.IntegerField(default=50, help_text='Host`s HDD total spase (Gb'),
        ),
        migrations.AddField(
            model_name='host',
            name='usb_devs',
            field=models.IntegerField(default=0, help_text='Amount of connected USB devices'),
        ),
        migrations.AlterField(
            model_name='host',
            name='measures',
            field=models.TextField(help_text='Collect measures of host`s parameters'),
        ),
    ]
